[package]
authors = ["Quentin Smith <quentin@mit.edu>"]
edition = "2018"
name = "discobiker"
version = "0.1.0"

[dependencies]
embassy = { version = "0.1.0", features = ["nightly", "defmt"]}
embassy-nrf = { version = "0.1.0", features = [ "nightly", "defmt", "nrf52840", "gpiote", "time-driver-rtc1" ]}
cortex-m        = { version = "0.7.3" }
cortex-m-rt = "0.7.0"
defmt = { version = "0.3", features = [] }
defmt-rtt = "0.3"
nrf-softdevice-defmt-rtt = { version = "0.1.0" }
panic-probe = { version = "0.3", features= ["print-defmt"] }
nrf-softdevice = { version = "0.1.0", features = ["defmt", "nrf52840", "s140", "ble-peripheral", "ble-central"] } # , "critical-section-impl"
nrf-softdevice-s140 = { version = "0.1.1" }
embedded-hal = "0.2.6"
embedded-storage = "0.3.0"
embedded-storage-async = "0.3.0"
futures = { version = "0.3.5", default-features = false }
fixed = "1.2.0"
heapless = "0.7.1"

[patch.crates-io]
embassy = { git = "https://github.com/embassy-rs/embassy" }
embassy-nrf = { git = "https://github.com/embassy-rs/embassy" }
embassy-macros = { git = "https://github.com/embassy-rs/embassy" }
nrf-softdevice = { git = "https://github.com/embassy-rs/nrf-softdevice" }
nrf-softdevice-s140 = { git = "https://github.com/embassy-rs/nrf-softdevice" }
nrf-softdevice-defmt-rtt = { git = "https://github.com/embassy-rs/nrf-softdevice" }
